import pg from "pg";

const HUMAN_APPROVAL_CONTEXT = "helmsman/human-approval";
const DEFAULT_REPOSITORY = "cindysi6699-svg/ai-scrum-lite";
const BASE_BRANCH = "agent-sandbox";

function arg(name) {
  const index = process.argv.indexOf(`--${name}`);
  return index >= 0 ? process.argv[index + 1] : undefined;
}

function requiredEnv(name) {
  const value = process.env[name];
  if (!value) {
    throw new Error(`${name} is required.`);
  }
  return value;
}

function repoParts() {
  const repository = process.env.GITHUB_REPOSITORY ?? DEFAULT_REPOSITORY;
  const [owner, repo] = repository.split("/");
  if (!owner || !repo) {
    throw new Error("GITHUB_REPOSITORY must be formatted as owner/repo.");
  }
  return { owner, repo };
}

async function github(path, init = {}) {
  const token = requiredEnv("GITHUB_TOKEN");
  const { owner, repo } = repoParts();
  const response = await fetch(`https://api.github.com/repos/${owner}/${repo}${path}`, {
    ...init,
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
      "X-GitHub-Api-Version": "2022-11-28",
      ...(init.headers ?? {}),
    },
  });

  if (!response.ok) {
    const detail = await response.text();
    throw new Error(`GitHub ${init.method ?? "GET"} ${path} failed: ${response.status} ${detail}`);
  }

  return response.json();
}

async function writePendingStatus(sha, targetUrl) {
  await github(`/statuses/${sha}`, {
    method: "POST",
    body: JSON.stringify({
      state: "pending",
      context: HUMAN_APPROVAL_CONTEXT,
      description: "Waiting for human acceptance in Helmsman.",
      target_url: targetUrl,
    }),
  });
}

function normalizeBranchPart(value) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

async function findTask(client) {
  const taskId = arg("task") ?? arg("task-id");
  const story = arg("story");

  if (taskId) {
    const result = await client.query(
      `
        SELECT t.*, b.title AS "backlogTitle"
        FROM "Task" t
        LEFT JOIN "BacklogItem" b ON b.id = t."backlogItemId"
        WHERE t.id = $1
        LIMIT 1
      `,
      [taskId],
    );
    return result.rows[0];
  }

  if (!story) {
    throw new Error("Pass --task <taskId> or --story US-13.");
  }

  const result = await client.query(
    `
      SELECT t.*, b.title AS "backlogTitle"
      FROM "Task" t
      JOIN "BacklogItem" b ON b.id = t."backlogItemId"
      JOIN "Sprint" s ON s.id = t."sprintId"
      WHERE b.title LIKE $1
        AND s.name ILIKE '%Sprint 3%'
      ORDER BY t."createdAt" ASC
      LIMIT 1
    `,
    [`${story}%`],
  );
  return result.rows[0];
}

async function findAgent(client, projectId, role, names) {
  const result = await client.query(
    `
      SELECT pm."userId", pm."displayName", u.name
      FROM "ProjectMember" pm
      JOIN "User" u ON u.id = pm."userId"
      WHERE pm."projectId" = $1 AND u.type = 'ai'
      ORDER BY pm."createdAt" ASC
    `,
    [projectId],
  );

  return (
    result.rows.find((row) => {
      const label = `${row.displayName ?? ""} ${row.name ?? ""}`.toLowerCase();
      return names.some((name) => label.includes(name));
    }) ??
    result.rows.find((row) => {
      const label = `${row.displayName ?? ""} ${row.name ?? ""}`.toLowerCase();
      return label.includes(role);
    }) ??
    result.rows[0]
  );
}

async function main() {
  const client = new pg.Client({
    connectionString: requiredEnv("DATABASE_URL"),
    ssl: { rejectUnauthorized: false },
  });

  await client.connect();

  try {
    const task = await findTask(client);
    if (!task) {
      throw new Error("Task not found.");
    }

    const storyCode = (task.backlogTitle?.match(/US-\d+/)?.[0] ?? task.id.slice(0, 6)).toUpperCase();
    const branch = `agent/${storyCode}-${normalizeBranchPart(task.title).slice(0, 36)}-${Date.now()}`;
    const baseRef = await github(`/git/ref/heads/${BASE_BRANCH}`);

    await github("/git/refs", {
      method: "POST",
      body: JSON.stringify({
        ref: `refs/heads/${branch}`,
        sha: baseRef.object.sha,
      }),
    });

    const artifactPath = `docs/sprints/sprint-3/agent-pr-artifacts/${storyCode}-${Date.now()}.md`;
    await github(`/contents/${artifactPath}`, {
      method: "PUT",
      body: JSON.stringify({
        message: `${storyCode}: agent-01 redline handoff`,
        content: Buffer.from(
          `# ${storyCode} agent handoff\n\nTask: ${task.title}\n\nGenerated by agent-01 for Sprint 3 redline validation.\n`,
        ).toString("base64"),
        branch,
      }),
    });

    const pr = await github("/pulls", {
      method: "POST",
      body: JSON.stringify({
        title: `${storyCode}: ${task.title}`,
        head: branch,
        base: BASE_BRANCH,
        body: [
          "Agent-01 generated this PR to exercise Helmsman human approval redline.",
          "",
          `Task: ${task.id}`,
        ].join("\n"),
      }),
    });

    await writePendingStatus(pr.head.sha, pr.html_url);

    const agent01 = await findAgent(client, task.projectId, "dev", ["agent-01", "dev agent 01"]);
    const agent02 = await findAgent(client, task.projectId, "qa", ["agent-02", "qa agent", "claude"]);
    const actorId = agent01?.userId ?? task.createdById;
    const assigneeId = agent02?.userId ?? task.assigneeId;

    await client.query("BEGIN");
    await client.query(
      `
        INSERT INTO "GithubRef"
          (id, "projectId", "taskId", branch, "headSha", "pullRequestUrl", "checksStatus", "redlineStatus", note, "createdById", "createdAt", "updatedAt")
        VALUES
          ('githubref_' || replace(gen_random_uuid()::text, '-', ''), $1, $2, $3, $4, $5, 'pending', 'pending', $6, $7, NOW(), NOW())
      `,
      [
        task.projectId,
        task.id,
        branch,
        pr.head.sha,
        pr.html_url,
        "Agent PR opened by scripts/agent-pr.mjs; waiting for human approval.",
        actorId,
      ],
    );
    await client.query(
      `
        UPDATE "Task"
        SET status = 'review', "assigneeId" = $1, "completedAt" = NOW(), "updatedAt" = NOW()
        WHERE id = $2
      `,
      [assigneeId, task.id],
    );
    await client.query(
      `
        INSERT INTO "TaskUpdate"
          (id, "taskId", "actorId", "previousStatus", "newStatus", progress, artifacts, "needsHumanDecision", "createdAt")
        VALUES
          ('taskupdate_' || replace(gen_random_uuid()::text, '-', ''), $1, $2, $3, 'review', $4, $5::jsonb, TRUE, NOW())
      `,
      [
        task.id,
        actorId,
        task.status,
        `Opened PR ${pr.html_url}; human approval status is pending; assigned to agent-02.`,
        JSON.stringify({
          pullRequestUrl: pr.html_url,
          branch,
          headSha: pr.head.sha,
        }),
      ],
    );
    await client.query("COMMIT");

    console.log(JSON.stringify({ taskId: task.id, branch, pullRequestUrl: pr.html_url, headSha: pr.head.sha }, null, 2));
  } catch (error) {
    await client.query("ROLLBACK").catch(() => {});
    throw error;
  } finally {
    await client.end();
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
